---
editor_options:
  markdown:
    wrap: 72
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}

#library(lme4) 
library(nlme) 
library(glmmTMB) 
library(ggplot2)
library(tidyverse)
library(dplyr)
library(magrittr)
library(easystats)
library(lmerTest)
library(stargazer)

library(effsize)
library(rcompanion)
library(cluster)
library(factoextra)
library(magrittr)
library(useful)
```

```{r}
options(scipen = 999)
```

```{r}
explain <- function(model) {
  print(performance(model))
  statistics <- anova(model)
  statistics$`Sum Sq` %<>% round(digits = 3)
  print(statistics)
  print(parameters(model, ci_method = "satterthwaite"))
  class(model) <- "lmerMod"
  stargazer(model, type = "text", star.cutoffs = c(0.05, 0.01, 0.001))
}
```

```{r}
#merged_data  <- read.table("merged_data_1.csv", header = TRUE, sep=",")
#merged_data  <- read.table("merged_data_2.csv", header = TRUE, sep=",")
#merged_data  <- read.table("merged_data_3.csv", header = TRUE, sep=",")
#merged_data  <- read.table("merged_data_4.csv", header = TRUE, sep=",")
merged_data  <- read.table("at_resolution.csv", header = TRUE, sep=",")

str(merged_data)

```

```{r}
merged_data %<>% rename(
  PR_size = PR_size.SLOC.
) 

```

```{r}

merged_data$time_to_merge_h <- as.integer(round(merged_data$time_to_merge_h))
merged_data$PR_size <- as.integer((merged_data$PR_size))
merged_data$project_age_month <- as.double((merged_data$project_age_month))   #I(merged_data$project_age_month*730)  
merged_data$is_gpt <- as.factor(merged_data$is_gpt)
```

```{r}
merged_data$project <- as.factor(merged_data$project)
merged_data$actor <- as.factor(merged_data$actor)

#merged_data$is_gpt <- as.logical(as.integer(merged_data$is_gpt))

#merged_data$is_gpt <- as.factor(merged_data$is_gpt)

str(merged_data)

```

```{r}

#lm_13.intercept <- lmer( scale(time_to_merge_h)  ~  is_gpt + scale(no_commits) + scale(PR_size)   + scale(no_changed_files) +  scale(project_age_month) + (1|project) , data = merged_data)
lm_13.intercept <- lmer( log1p(time_to_merge_h)  ~  (is_gpt) + log1p(no_commits) + log1p(PR_size)   + log1p(no_changed_files) + log1p(project_age_month) +  ( 1|project) , data = merged_data)

lm_14.intercept <- lmer( log1p(time_to_merge_h)  ~  (is_gpt) + log1p(no_commits) + log1p(PR_size)   + log1p(no_changed_files) + log1p(project_age_month) +  ( 1+ is_gpt|project) , data = merged_data)

```

```{r}
explain(lm_13.intercept)
#explain(lm_14.intercept)
```

```{r}
#plot(lm_13.intercept)
#plot(lm_13.intercept, which = 2)
sub_data = merged_data %>%
    filter(project_age_month == 12)

(split_plot <- ggplot(aes(project_age_month,  mean(time_to_merge_h)), data = merged_data) + 
  geom_point() + 
  facet_wrap(~ is_gpt) + # create a facet for each mountain range
  xlab("project age") + 
  ylab("time to merged"))

```

```{r}

#hist(merged_data$is_gpt)

merged_data$time_to_merge_h_predit <- predict(lm_13.intercept, merged_data)

ggplot() +
  theme_minimal() +
  geom_point(data = merged_data,
             aes(x = factor(is_gpt),  y = time_to_merge_h)) + 
  geom_point(data = merged_data,
               aes(x = factor(is_gpt) , y = time_to_merge_h_predit),
               color = 'blue', alpha = 0.5) 
```

```{r}
data_subset <-
    merged_data %>%
    mutate(lm_predict = predict(lm_14.intercept),
           lmer_predict = predict(lm_13.intercept)) #%>%
    #filter(is_gpt == 1)

ggplot(data_subset,
       aes(x = is_gpt, y = time_to_merge_h, color = as_factor(is_gpt))) +
    geom_point() +
    geom_line(aes(x = is_gpt, y = lm_predict)) +
    geom_line(aes(x = is_gpt, y = lmer_predict), linetype = 'dashed') +
    xlab("Kindergarten math score") +
    ylab("Math gain later in school") +
    theme_bw() +
    scale_color_manual("Is GPT", values = c("red", "blue"))
```

```{r}
d <- merged_data

d$is_gpt <- factor(d$is_gpt)
ggplot(d, aes(x=is_gpt, y=log1p(time_to_merge_h))) + 
geom_violin(fill ='Gray') + geom_boxplot(width=0.2, color = 'black')+ 
stat_summary(fun = "mean", geom="point", size=3, color="red")+ 
labs(x = "GPT for assistance ", y = "Log of Time to Merge")
```

```{r}
merge_data_gpt_0 <- merged_data %>% filter(is_gpt == 0)
merge_data_gpt_1 <- merged_data %>% filter(is_gpt == 1)

wilcox.test(merge_data_gpt_0$time_to_merge_h, merge_data_gpt_1$time_to_merge_h)


#wilcox.test(time_to_merge_h ~ is_gpt, data = merged_data, exact = "exact")
```

```{r}
mean_0 <- mean(merge_data_gpt_0$time_to_merge_h)
mean_1 <- mean(merge_data_gpt_1$time_to_merge_h)
print(paste0('mean value in days time-to-merge gpt-for-assistance: ', round (mean_0/24,2)))

print(paste0('mean value in days time-to-merge gpt-for-assistance: ', round(mean_1/24,2)))

```

```{r}
mean_project_age_0 <- mean(merge_data_gpt_0$project_age_month)
mean_project_age_1 <- mean(merge_data_gpt_1$project_age_month)

print(paste0('mean value in months project age gpt-no-for-assistance: ', round (mean_project_age_0,2)))

print(paste0('mean value in months project age gpt-for-assistance: ', round(mean_project_age_1,2)))

```

```{r}
cliffDelta(time_to_merge_h ~ is_gpt, data=merged_data)

cliffDelta(time_to_merge_h ~ is_gpt, data=merged_data, ci= TRUE)

cliff.delta(d = merged_data$time_to_merge_h,
            f = merged_data$is_gpt)
```

```{r}
 
  #merged_data$pull_number <- factor(merged_data$pull_number )
  #merged_data_test <- merged_data[merged_data[-c(1, 2, 3)] ]
                                  #merged_data %>% select(as.numeric(merged_data$no_commits))
  merged_data
  merged_data_test <- merged_data[-c( 1, 2, 3 )]
  merged_data_test
```

```{r}
set.seed(125)
pulls <- merged_data_test[, which(names(merged_data_test) != "is_gpt") ]
#pulls <- pulls[, which(names(pulls) != "project_age_month") ]
#pulls <- pulls[, which(names(pulls) != "PR_size") ]
#pulls <- pulls[, which(names(pulls) != "no_changed_files") ]
pulls_k <- kmeans(x=pulls, centers=4)
pulls_k <- na.omit(pulls_k)
pulls_k

```

```{r}

print(pulls_k)

x <-c(41, 7, 1088, 23)
mad(x)

```

```{r}


aggregate(merged_data_test, by=list(cluster=pulls_k$cluster), mean)
dd <- cbind(merged_data_test, cluster = pulls_k$cluster)
head(dd)
head(pulls_k$cluster,4)

```

```{r}
set.seed(278613)
pulls <- merged_data_test[, which(names(merged_data_test) != "is_gpt") ]
pulls <- pulls[, which(names(pulls) != "project_age_month") ]
pulls <- pulls[, which(names(pulls) != "PR_size") ]
pulls <- pulls[, which(names(pulls) != "no_commits") ]
pulls_k <- kmeans(x=pulls, centers=1)
pulls_k <- na.omit(pulls_k)
pulls_k
```

```{r}

plot(pulls_k, data=merged_data_test, class='is_gpt')

```

```{r}
set.seed(278613)
pulls <- merged_data_test[, which(names(merged_data_test) != "is_gpt") ]
pulls <- pulls[, which(names(pulls) != "project_age_month") ]
#pulls <- pulls[, which(names(pulls) != "PR_size") ]
pulls <- pulls[, which(names(pulls) != "no_changed_files") ]
pulls <- pulls[, which(names(pulls) != "no_commits") ]
pulls_k <- kmeans(x=pulls, centers=1)
pulls_k <- na.omit(pulls_k)
pulls_k


```

```{r}
plot(pulls_k, data=merged_data_test, class='is_gpt')
```

```{r}
set.seed(278613)
pulls <- merged_data_test[, which(names(merged_data_test) != "is_gpt") ]
#pulls <- pulls[, which(names(pulls) != "project_age_month") ]
pulls <- pulls[, which(names(pulls) != "PR_size") ]
pulls <- pulls[, which(names(pulls) != "no_changed_files") ]
pulls <- pulls[, which(names(pulls) != "no_commits") ]
pulls_k <- kmeans(x=pulls, centers=1)
pulls_k <- na.omit(pulls_k)
pulls_k


```

```{r}
plot(pulls_k, data=merged_data_test, class='is_gpt')
```

```{r}
z <- pulls[,-c(1,1)]
pulls
#apply(pulls[c("project_age_month","no_commits","PR_size","no_changed_files","time_to_merge_h")], 2, mean)
means <- apply(pulls[c("no_commits","time_to_merge_h")], 2, mean)
#means <- apply( z, 2, mean)
#sds <- apply(z,2,sd)
sds <- apply(pulls[c("no_commits","time_to_merge_h")],2,sd)
#nor <- scale(z,center=means,scale=sds)
nor <- scale(pulls[c("no_commits","time_to_merge_h")], center=means, scale=sds)

pulls_k <- kmeans(x=nor, centers=3)

plot(pulls_k, data=merged_data_test, class='is_gpt')
```

```{r}
ot<-nor
fviz_nbclust(nor, kmeans, method = "wss")

fviz_nbclust(nor, kmeans, method = "silhouette")


gap_stat <- clusGap(nor, FUN = kmeans, nstart = 25,
                    K.max = 10, B = 50)
fviz_gap_stat(gap_stat)

```

```{r}
sds
means

#model_reg <- glmmTMB(time_to_merge_h ~ is_gpt + no_commits + PR_size + no_changed_files, data = merged_data)
#model_mix_0 <- glmmTMB(time_to_merge_h ~ is_gpt + (1|project), data = merged_data)
#model_mix_1 <- glmmTMB(time_to_merge_h ~ is_gpt + no_commits + (1|project), data = merged_data)
#model_mix_2 <- glmmTMB(time_to_merge_h ~ is_gpt + no_commits + PR_size +  (1|project), data = merged_data)
#model_mix_3 <- glmmTMB(time_to_merge_h ~ is_gpt + no_commits + PR_size + no_changed_files + (1|project), data = merged_data)
#model_mix_4 <- glmmTMB(time_to_merge_h ~ is_gpt + no_commits + PR_size + no_changed_files + (1|actor_pull), data = merged_data)
```

```{r}
#summary(model_mix_0)
#anova(model_mix_0, model_mix_1,test='Chisq')
```

```{r}
#summary(model_mix_1)
#anova(model_mix_1, model_mix_2,test='Chisq')
```

```{r}
#summary(model_mix_2)
#anova(model_mix_1,model_mix_2, model_mix_3,test='Chisq')
```

```{r}
#summary(model_mix_3)
#anova(model_mix_4,model_mix_3,test='Chisq')
```
